- name: Christopher J. Wright
  email: cjwright4242gh@gmail.com
  num_commits: 70
  first_commit: 2018-09-27 11:05:14
  alternate_emails:
  - cjwright4242@gmail.com
  aliases:
  - christopher
- name: Simon Billinge
  email: simon.billinge@gmail.com
  alternate_emails:
  - sbillinge@users.noreply.github.com
  num_commits: 13
  first_commit: 2020-08-06 07:06:54
  github: sbillinge
- name: Songsheng Tao
  email: st3107@columbia.edu
  alternate_emails:
  - 37090959+st3107@users.noreply.github.com
  num_commits: 8
  first_commit: 2020-08-05 18:11:47
  github: st3107
